version: "2"
services:
  php:
    build: .
    container_name: "apache_php"
    image: php:8.1.17-apache
    volumes:
      - ./:/www/html/
    ports:
      - 8180:80
  db:
    image: mariadb:10.5
    container_name: "mariadb-server"
    restart: always
    volumes:
      - /banco.sql:/docker-entrypoint-initdb.d/banco.sql
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
    ports:
        - 3304:3306
