-- MySQL Script generated by MySQL Workbench
-- qui 06 nov 2025 16:50:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(100) NOT NULL,
  `tamanho` VARCHAR(100) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `estoque` INT(10) NOT NULL,
  `desconto` DECIMAL(3,2) NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `avaliacao` DECIMAL(2,1) NULL,
  `comentario` VARCHAR(500) NULL,
  `tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(100) NULL,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `isadmin` TINYINT NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(17) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `tb_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_tb_cliente_tb_usuario1_idx` (`tb_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_cliente_tb_usuario1`
    FOREIGN KEY (`tb_id_usuario`)
    REFERENCES `mydb`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `cupom` VARCHAR(45) NULL,
  `valor_venda` VARCHAR(45) NULL,
  `tb_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_tb_venda_tb_cliente2_idx` (`tb_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_venda_tb_cliente2`
    FOREIGN KEY (`tb_id_cliente`)
    REFERENCES `mydb`.`tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `salario` DECIMAL(10,2) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `tb_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_tb_funcionario_tb_usuario1_idx` (`tb_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_funcionario_tb_usuario1`
    FOREIGN KEY (`tb_id_usuario`)
    REFERENCES `mydb`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_foto` (
  `id_table1` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `tb_id_produto` INT NOT NULL,
  PRIMARY KEY (`id_table1`),
  INDEX `fk_table1_tb_produto1_idx` (`tb_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_table1_tb_produto1`
    FOREIGN KEY (`tb_id_produto`)
    REFERENCES `mydb`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(100) NULL,
  `tb_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_td_endereco_td_usuario1_idx` (`tb_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_td_endereco_td_usuario1`
    FOREIGN KEY (`tb_id_usuario`)
    REFERENCES `mydb`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_venda_produto` (
  `tb_id_venda` INT NOT NULL,
  `tb_id_produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`tb_id_venda`, `tb_id_produto`),
  INDEX `fk_tb_venda_has_tb_produto_tb_produto1_idx` (`tb_id_produto` ASC) VISIBLE,
  INDEX `fk_tb_venda_has_tb_produto_tb_venda1_idx` (`tb_id_venda` ASC) VISIBLE,
  CONSTRAINT `fk_tb_venda_has_tb_produto_tb_venda1`
    FOREIGN KEY (`tb_id_venda`)
    REFERENCES `mydb`.`tb_venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_venda_has_tb_produto_tb_produto1`
    FOREIGN KEY (`tb_id_produto`)
    REFERENCES `mydb`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

