-- MySQL Script generated by MySQL Workbench
-- seg 23 jun 2025 16:21:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(100) NOT NULL,
  `tamanho` VARCHAR(100) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `estoque` INT(10) NOT NULL,
  `desconto` DECIMAL(3,2) NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `avaliacao` DECIMAL(2,1) NULL,
  `comentario` VARCHAR(500) NULL,
  `tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(17) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_venda` (
  `id_compras` INT NOT NULL AUTO_INCREMENT,
  `cupom` VARCHAR(45) NULL,
  `valor da venda` VARCHAR(45) NULL,
  `tb_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_compras`),
  INDEX `fk_tb_venda_tb_cliente2_idx` (`tb_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_venda_tb_cliente2`
    FOREIGN KEY (`tb_id_cliente`)
    REFERENCES `mydb`.`tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_compras_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_compras_produto` (
  `tb_id_produto` INT NOT NULL,
  `quantidade` INT(10) NOT NULL,
  `tb_id_compras` INT NOT NULL,
  PRIMARY KEY (`tb_id_produto`, `tb_id_compras`),
  INDEX `fk_td_compras_has_td_produto_td_produto1_idx` (`tb_id_produto` ASC) VISIBLE,
  INDEX `fk_tb_compras_produto_tb_venda1_idx` (`tb_id_compras` ASC) VISIBLE,
  CONSTRAINT `fk_td_compras_has_td_produto_td_produto1`
    FOREIGN KEY (`tb_id_produto`)
    REFERENCES `mydb`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_compras_produto_tb_venda1`
    FOREIGN KEY (`tb_id_compras`)
    REFERENCES `mydb`.`tb_venda` (`id_compras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `salario` DECIMAL(5,2) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `data_nacimento` DATE NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(100) NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `isadmin` TINYINT NOT NULL,
  `tb_id_cliente` INT NOT NULL,
  `tb_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuario_tb_cliente1_idx` (`tb_id_cliente` ASC) VISIBLE,
  INDEX `fk_usuario_funcionario1_idx` (`tb_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tb_cliente1`
    FOREIGN KEY (`tb_id_cliente`)
    REFERENCES `mydb`.`tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_funcionario1`
    FOREIGN KEY (`tb_id_funcionario`)
    REFERENCES `mydb`.`tb_funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_fotos` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `tb_id_produto` INT NOT NULL,
  PRIMARY KEY (`idtable1`),
  INDEX `fk_table1_tb_produto1_idx` (`tb_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_table1_tb_produto1`
    FOREIGN KEY (`tb_id_produto`)
    REFERENCES `mydb`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(100) NULL,
  `tb_id_usuario` INT NOT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_td_endereco_td_usuario1_idx` (`tb_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_td_endereco_td_usuario1`
    FOREIGN KEY (`tb_id_usuario`)
    REFERENCES `mydb`.`tb_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

