-- MySQL Script generated by MySQL Workbench
-- qui 10 abr 2025 08:29:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(100) NOT NULL,
  `tamanho` VARCHAR(5) NOT NULL,
  `fotos` VARCHAR(100) NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL,
  `estoque` DECIMAL(10) NOT NULL,
  `desconto` DECIMAL(2) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `local` VARCHAR(100) NOT NULL,
  `avaliacao` VARCHAR(45) NULL,
  `comentario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cliente` (
  `id_cliente` INT NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(17) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_venda` (
  `id_compras` INT NOT NULL AUTO_INCREMENT,
  `cupom` VARCHAR(45) NULL,
  `valor da venda` VARCHAR(45) NULL,
  `tb_cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_compras`, `tb_cliente_id_cliente`),
  INDEX `fk_tb_venda_tb_cliente1_idx` (`tb_cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_venda_tb_cliente1`
    FOREIGN KEY (`tb_cliente_id_cliente`)
    REFERENCES `mydb`.`tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_compras_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_compras_produto` (
  `td_compras_id_compras` INT NOT NULL,
  `td_produto_idtd_produto` INT NOT NULL,
  `quantiddade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`td_compras_id_compras`, `td_produto_idtd_produto`),
  INDEX `fk_td_compras_has_td_produto_td_produto1_idx` (`td_produto_idtd_produto` ASC) VISIBLE,
  INDEX `fk_td_compras_has_td_produto_td_compras1_idx` (`td_compras_id_compras` ASC) VISIBLE,
  CONSTRAINT `fk_td_compras_has_td_produto_td_compras1`
    FOREIGN KEY (`td_compras_id_compras`)
    REFERENCES `mydb`.`tb_venda` (`id_compras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_td_compras_has_td_produto_td_produto1`
    FOREIGN KEY (`td_produto_idtd_produto`)
    REFERENCES `mydb`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `salario` DECIMAL(5,2) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `data_nacimento` DATE NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `isadmin` TINYINT NOT NULL,
  `tb_cliente_id_cliente` INT NOT NULL,
  `funcionario_idfuncionario` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `tb_cliente_id_cliente`, `funcionario_idfuncionario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuario_tb_cliente1_idx` (`tb_cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_usuario_funcionario1_idx` (`funcionario_idfuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tb_cliente1`
    FOREIGN KEY (`tb_cliente_id_cliente`)
    REFERENCES `mydb`.`tb_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
